baseURL = 'https://tawkie.fr/'
languageCode = 'fr'
title = 'Tawkie'
disableKinds = ['taxonomy', 'term']
defaultContentLanguage = 'fr'

[[module.mounts]]
  source = 'assets'
  target = 'assets'



[languages]
  [languages.fr]
    languageName = 'Français'
    weight = 2
  [languages.en]
    languageName = 'English'
    weight = 1



