baseURL = 'https://tawkie.fr/'
languageCode = 'fr'
title = 'Tawkie'
disableKinds = ['taxonomy', 'term']
defaultContentLanguage = 'fr'

[params]


[languages]
  [languages.fr]
    languageName = 'Français'
    weight = 1
  [languages.en]
    languageName = 'English'
    weight = 2



